version: '3.3'

services:
  # Database
  db:
    image: mysql:5.7
    container_name: ${MYSQL_CONTAINER_NAME}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: .env

  # wordpress
  # wordpressとPHPのバージョンはタグで指定
  # https://hub.docker.com/_/wordpress/
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: ${WORDPRESS_CONTAINER_NAME}
    ports:
      - "${APP_PORT}:80"
    restart: always
    env_file: .env
    volumes:
      - ./${WORDPRESS_DIR}:/var/www/html
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  cli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    container_name: ${WP_CLI_CONTAINER_NAME}
    user: xfs
volumes:
  db_data: {}
  php: {}
  wordpress: {}